---
title: Prebid.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Prebid
version: 1.0.0
license: Apache License
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
headerLinks:
- title: GitHub
  url: https://github.com/prebid
footerLinks:
- title: GitHub
  url: https://github.com/prebid/
header:
  color1: "#3b88c3"
  trianglify: false
analytics:
  account: 
  domain: 
githubButton:
  user: prebid
  repo: Prebid.js
twitter:
  enabled: true
  via: 
  hash: prebidjs
  account: 
facebook:
  enabled: false
  profileUrl: 
markdown: kramdown
nav_sections:
- top_nav: beta
  code: current
  name: CURRENT BETA
- top_nav: beta
  code: past
  name: PAST BETA
- top_nav: dev_docs
  code: quick-start
  name: DEVELOPER QUICK START
- top_nav: dev_docs
  code: prebid-video
  name: PREBID VIDEO (BETA)
- top_nav: dev_docs
  code: prebid-native
  name: PREBID NATIVE (ALPHA)
- top_nav: dev_docs
  code: prebid-server
  name: PREBID SERVER
- top_nav: dev_docs
  code: prebid-amp
  name: PREBID FOR AMP (ALPHA)
- top_nav: dev_docs
  code: troubleshooting
  name: TROUBLESHOOTING
- top_nav: dev_docs
  code: reference
  name: REFERENCE
- top_nav: dev_docs
  code: features
  name: FEATURES
- top_nav: dev_docs
  code: adapters
  name: ADAPTERS
- top_nav: overview
  code: intro
  name: INTRO
- top_nav: overview
  code: postbid
  name: POST-BID
- top_nav: overview
  code: analytics
  name: ANALYTICS
- top_nav: overview
  code: studies
  name: LATEST STUDIES
- top_nav: adops
  code: tutorials
  name: AD OPS TUTORIALS
- top_nav: adops
  code: reference
  name: REFERENCE
- top_nav: support
  code: support
  name: SUPPORT
- top_nav: principles
  code: principles
  name: PRINCIPLES
- top_nav: download
  code: download
  name: DOWNLOAD
- top_nav: modules
  code: modules
  name: MODULES
- top_nav: prebid-mobile
  code: prebid-mobile
  name: PREBID MOBILE
- top_nav: prebid-mobile
  code: prebid-mobile-pbs
  name: PREBID SERVER
- top_nav: prebid-mobile
  code: prebid-mobile-ios
  name: FOR IOS
- top_nav: prebid-mobile
  code: prebid-mobile-android
  name: FOR ANDROID
- top_nav: prebid-mobile
  code: prebid-mobile-adops
  name: FOR ADOPS
- top_nav: prebid-mobile
  code: prebid-mobile-contributors
  name: FOR CONTRIBUTORS
port: 8080
exclude:
- README.md
- LICENSE
- bower.json
- Gemfile.lock
- Gemfile
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
